# export DOCKER_BUILDKIT=0
# export COMPOSE_DOCKER_CLI_BUILD=0
# docker-compose up --build

version: '3.8'
services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_ENV=chofs
      - DD_SERVICE=chofs-api
      - DD_VERSION=20260122-1121
      - DD_LOGS_INJECTION=true
      - DD_RUNTIME_METRICS_ENABLED=true
      - DD_DYNAMIC_INSTRUMENTATION_ENABLED=true
      - DD_EXCEPTION_REPLAY_ENABLED=true
      - DD_CODE_ORIGIN_FOR_SPANS_ENABLED=true
      - DD_PROFILING_ENABLED=true
      - DD_GIT_REPOSITORY_URL=github.com/GiovanniYuriMita/Datadog-APM-Setups
      - DD_GIT_COMMIT_SHA=${COMMIT_SHA}
      - DD_APPSEC_ENABLED=true
    depends_on:
      - datadog-agent

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      # - DD_APM_REPLACE_TAGS=[{"name":"error.stack","pattern":"\\(Array, [\\s\\S]*?, Array\\)","repl":"(Array, [Sensitive Data Redacted], Array"}]
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_HOSTNAME=datadog-agent
    ports:
      - "8126:8126/tcp" # APM
      - "8125:8125/udp" # DogStatsD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Collect logs from Docker